title: "Детский национально-этнографический центр «Родники Кузбасса»"
header_title_main: "Детский национально-этнографический центр «Родники Кузбасса»"
header_title_sub: "МБОУ ДО «Дворец детского творчества» имени Ю.А. Гагарина», Прокопьевский городской округ, Кемеровская область-Кузбасс"
footer_text: "Адрес: 653001, Российская Федерация, Кемеровская область – Кузбасс, Прокопьевский ГО, улица Артема, дом 8<br>Телефон: +7 (384) 661-26-28<br>Электронная почта: center-rodniki@mail.ru"
header_logo: "/assets/images/site-title-logo.jpg"
lang: ru
markdown: kramdown
